# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3370e05990ec799b41c73176c38856c7f22990eae4969adaaee1e17b70382f1072a45845508a1c7295899c581d680f9446bf9fb20a6429133ac2966dc2830868

test:
  secret_key_base: 3a6ffe45a23efc3403fdba2694f6cc8b5a75ccf74f3e8dbd28c996e4af86e731dcc82bdbb4bd48ccbf8b8c3af256792338904f4f0eaa8664cb1f0eb1fc037774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
